apiVersion: v1
kind: Pod
metadata: 
  name: my-app-pod
  labels:
    app: my-app
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: postgres
      image: postgres
      env: 
       - name: POSTGRES_PASSWORD
         value: mysecretpassword

